src/pjt/Router/subpage/MapInfo.jsx

MapInfo component 제작 1차

---

src/App.js
src/pjt/Router/css/main.css
src/pjt/Router/subpage/MapInfo.jsx

MapInfo 제작 2번

---

src/App.js
src/pjt/Router/api/TmapTrans.js
src/pjt/Router/css/TrafficInfo.css
src/pjt/Router/subpage/TrafficInfo.jsx

trafficinfo

---

src/pjt/Router/SubPage.jsx
src/pjt/Router/css/subPage.css
src/pjt/Router/css/weather.css
src/pjt/Router/subpage/WeatherInfo.jsx

ONETEAMBTC-48 필터에서 지역값받음 & 영어로 변환해서 API 호출 & 날씨 XHTML 뼈대

ONETEAMBTC-48 필터에서 지역값받음 & 영어로 변환해서 API 호출 & 날씨 XHTML 뼈대

---

src/pjt/Router/subpage/WeatherForecastInfo.jsx
src/pjt/Router/subpage/WeatherInfo.jsx

ONETEAMBTC-49 페이지 렌더링 비동기 수정 및 배열로 데이터 저장, 예상 날씨 리스트 컴포넌트 분리

ONETEAMBTC-49 페이지 렌더링 비동기 수정 및 배열로 데이터 저장, 예상 날씨 리스트 컴포넌트 분리

---

src/pjt/Footer.jsx
src/pjt/Router/Buttons.jsx
src/pjt/Router/Main_01.jsx
src/pjt/Router/SubPage.jsx
src/pjt/Router/css/footer.css
src/pjt/Router/css/main.css
src/pjt/Router/subpage/MapInfo.jsx

ONETEAMBTC-53 맵에 생성된 마크 위,경도 데이터 넘기기 완료

ONETEAMBTC-53 맵에 생성된 마크 위,경도 데이터 넘기기 완료

---

public/traffic.html
src/pjt/Router/api/TmapTrans.js
src/pjt/Router/css/TrafficInfo.css
src/pjt/Router/css/subPage.css
src/pjt/Router/subpage/TrafficInfo.jsx
src/pjt/Router/subpage/WeatherInfo.jsx

ONETEAMBTC-51 클릭한 마커의 위치 정보를 받아 길찾기 결과  띄움

ONETEAMBTC-51 클릭한 마커의 위치 정보를 받아 길찾기 결과  띄움

---

src/pjt/Router/subpage/TrafficInfo.jsx
src/pjt/Router/subpage/TrafficLocationName.jsx
src/pjt/Router/subpage/WeatherInfo.jsx

ONETEAMBTC-51 결과 로딩중일때 결과 로딩중이라는 문구를 띄움 & 길찾기 결과가 없을 시에 결과가 없습니다 문구 띄움
둘 다 훅 사용해서 문구 띄움

ONETEAMBTC-51 결과 로딩중일때 결과 로딩중이라는 문구를 띄움 & 길찾기 결과가 없을 시에 결과가 없습니다 문구 띄움

---

src/App.js
src/pjt/Footer.jsx
src/pjt/Header.jsx
src/pjt/Router/Buttons.jsx
src/pjt/Router/Main_01.jsx
src/pjt/Router/SubPage.jsx
src/pjt/Router/buttons.css
src/pjt/Router/subpage/MapInfo.jsx
src/pjt/Router/subpage/Sidebar.jsx

ONETEAMBTC-13 메인 컴포넌트 버튼 활성화 및 클릭시 변수 전달 기능 구현 완료

ONETEAMBTC-13 메인 컴포넌트 버튼 활성화 및 클릭시 변수 전달 기능 구현 완료

---

src/App.js
src/pjt/Router/Main_01.jsx
src/pjt/Router/subpage/CityInfo.jsx
src/pjt/Router/subpage/Sidebar.jsx

ONETEAMBTC-46 사이드바 수정

---

src/pjt/Router/subpage/WeatherForecastInfo.jsx
src/pjt/Router/subpage/WeatherInfo.jsx

ONETEAMBTC-49 날씨 데이터 화면에 더 추가

---

src/pjt/Router/css/style.css
src/pjt/Router/subpage/Sidebar.jsx

ONETEAMBTC-55 SideBar 컴포넌트 CSS 수정

ONETEAMBTC-55 SideBar 컴포넌트 CSS 수정

---

src/pjt/Router/SubPage.jsx
src/pjt/Router/subpage/CityInfo.jsx
src/pjt/Router/subpage/MapInfo.jsx
src/pjt/Router/subpage/Sidebar.jsx

ONETEAMBTC-56 위 경도마커 중간작업

---

src/pjt/Router/css/TrafficInfo.css

ONETEAMBTC-52 길찾기 css 수정

---

src/pjt/Router/subpage/MapInfo.jsx

ONETEAMBTC-57 City_info로 부터 장소 클릭 시, 해당 위치 마커 추가 및 모든 마커의 상황 별 마커 이미지 적용

ONETEAMBTC-57 City_info로 부터 장소 클릭 시, 해당 위치 마커 추가 및 모든 마커의 상황 별 마커 이미지 적용

---

src/pjt/Router/subpage/CityInfo.jsx

ONETEAMBTC-58 데이터 로딩 중 띄우기

---

src/pjt/Router/css/TrafficInfo.css
src/pjt/Router/subpage/TrafficInfo.jsx
src/pjt/Router/subpage/TrafficResultList.jsx

ONETEAMBTC-52 길찾기 className css수정

ONETEAMBTC-52 길찾기 className css수정

---

package-lock.json
package.json
src/pjt/Router/SubPage.jsx
src/pjt/Router/css/TrafficInfo.css
src/pjt/Router/subpage/TrafficInfo.jsx
src/pjt/Router/subpage/TrafficLocationName.jsx
src/pjt/Router/subpage/TrafficResultList.jsx

ONETEAMBTC-61 현위치 출발 및 도착 입력 기능

ONETEAMBTC-61 현위치 출발 및 도착 입력 기능

---

package-lock.json
package.json
src/pjt/Router/subpage/CityInfo.jsx

ONETEAMBTC-64 failed to fetch 에러 -> fetch-retry로 5번 재시도

ONETEAMBTC-64 failed to fetch 에러 -> fetch-retry로 5번 재시도

---

src/pjt/Router/css/TrafficInfo.css
src/pjt/Router/css/weather.css
src/pjt/Router/subpage/MapInfo.jsx
src/pjt/Router/subpage/TrafficInfo.jsx
src/pjt/Router/subpage/WeatherInfo.jsx
src/pjt/Router/subpage/WeatherInfoList.jsx

ONETEAMBTC-66 WeatherInfo CSS 최종 수정 완료

ONETEAMBTC-66 WeatherInfo CSS 최종 수정 완료

---

src/pjt/Router/css/sidebar.css
src/pjt/Router/css/subPage.css
src/pjt/Router/css/subfooter.css
src/pjt/Router/css/subheader.css
src/pjt/Router/subpage/Sidebar.jsx
src/pjt/SubFooter.jsx

ONETEAMBTC-69 CSS 최종 작업 완료

---

src/pjt/Router/Buttons.jsx
src/pjt/Router/Main_01.jsx
src/pjt/Router/css/main.css
src/pjt/Router/css/subfooter.css
src/pjt/Router/css/subheader.css
src/pjt/Router/subpage/TrafficInfo.jsx

ONETEAMBTC-70 subpage header, footer 추가 수정

ONETEAMBTC-70 subpage header, footer 추가 수정

---

src/pjt/MainFooter.jsx
src/pjt/Router/css/mainfooter.css
src/pjt/Router/css/subfooter.css
src/pjt/SubFooter.jsx

ONETEAMBTC-70 하단 푸터 클릭시 팝업 추가

---

src/pjt/Router/subpage/Sidebar.jsx

ONETEAMBTC-70 상세지역 버튼 토글링 + 관광지->테마별

ONETEAMBTC-70 상세지역 버튼 토글링 + 관광지->테마별

---

src/App.js
src/pjt/Router/css/Slider.css
src/pjt/Router/subpage/Sidebar.jsx

ONETEAMBTC-70 지역 및 세부지역 추가

---

public/index.html
src/App.js
src/pjt/Router/Buttons.jsx
src/pjt/Router/Main_01.jsx
src/pjt/Router/css/buttons.css
src/pjt/Router/css/main.css
src/pjt/Router/css/slider/mainPageSlider.css
src/pjt/Router/subpage/MapInfo.jsx
src/pjt/Router/subpage/Sidebar.jsx
src/pjt/Router/subpage/WeatherInfo.jsx

ONETEAMBTC-71 디테일 수정 완료
